apiVersion: v1
kind: Pod
metadata:
  name: cond-test-pod
spec:
  containers:
    - name: httpd
      image: httpd
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: sdk
              key: special.how


