apiVersion: v1
kind: Pod
metadata:
  name: cond-test-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how


