apiVersion: v1 
kind: Deployment
metadata:
  name: k8sdemo
  namespace: my-first
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80
