apiVersion: v1
kind: Pod
metadata:
  name: htcongfig
spec:
  containers:
    - name: httpd
      image: httpd
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
restartPolicy: Never



